---
title: De Effecten van Suiker op de CO2 Productie van Bakkersgist

author: |
  | Arjan Koens $^1$, Ivar Lottman $^1$, Stijn Vermeulen $^2$
  | $^1$Hanzehogeschool

lang: nl # dit zorgt er voor dat "abstract" "samenvatting" gaat heten

abstract: |
  Geef hier je samenvatting in maximaal 150 woorden. Het is een samenvatting van het hele artikel; niet alleen de resultaten! Begin met het belang van dit onderzoek, dan hoe het onderzoek is aangepakt en de belangrijkste resultaten en eindig met de implicaties ervan voor de wetenschap/de maatschappij. Neem nooit figuren of tabellen op in de samenvatting.

bibliography: gist_suiker_effect.bib # naam van je .bib file. Deze moet hetzelfde zijn als je Rmd bestandsnaam

output:
  bookdown::pdf_document2:
    keep_tex: false    # set this to true if you want to investigate the generated tex
    toc: false         # table of contents
    fig_caption: true  # includes figure captions with numbering in output
    includes:  
        in_header: include_tex_header.tex #will include rules for linespacing and figure floating

---
# Introductie
Gist is een micro-orgasme dat al duizenden jaren wordt gebruikt door mensen voor verschillende applicaties. Voor het maken van brood, om lucht in het deeg te krijgen. Voor het maken van alcoholische dranken. Die door de alcohol veiliger waren om te drinken dan water. Om een degelijk resultaat te krijgen bij deze applicaties van gist is het dan ook van belang om te weten wat de ideale omstandigheden van gist zijn. Om deze ideale omstandigheden te bepalen wordt er in dit rapport gekeken de $CO_2$ van bakkersgist in verschillende zout en suiker concentraties. Waar suiker als voeding voor gist functioneert en zout als extra stress factor.

De opstelling van dit onderzoek is gebaseerd op het onderzoek \cite{Jerry2017} waar $CO_2$ productie van bakkersgist op verschillende suiker concentraties is onderzocht. Om dit als alternatief $CO_2$ productie medium te kunnen gebruiken in de BG-Sentinel® muggen val.

Dit rapport dient om een optimaal suiker concentratie te vinden voor bakkersgist die resulteert in de snelste $CO_2$ productie. 


# Materialen en Methoden


# Resultaten



# Discussie en Conclusies


# Online bijlagen



## Wordcount
```{r wordcount, message=FALSE}
#install.packages(devtools)
#devtools::install_github("benmarwick/wordcountaddin", type = "source", dependencies = TRUE)
wordcountaddin:::text_stats()
```

# Referenties

